### PR TITLE
Module4 STL

### PR DESCRIPTION
**Pull request by boruno**
Two tasks done, 8 in WIP state, will be ready soon.

### CODE REVIEW

**Review by eupp — COMMENTED** [review]
I checked approx. half of the prepared tasks. I will have a look at the remaining tasks later. 
Overall good job, the text of the theory materials improved significantly compared to the module 3!

File: StandardLibraryEssentials/StandardTemplateLibrary/UnorderedContainers/task.md [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+    // print all elements, order is not guaranteed
+    for (const auto& s : set) {
+        std::cout << s << std::endl;
+    }
+}
+```
+
+You need to implement a small caching system. It is defined in `/include/Cache.h` file. Since [cache](https://en.wikipedia.org/wiki/Cache_(computing)) is very fast type of storage, in which we will frequently search data, `std::unordered_map` is a good choice for this task.
+
+You need to implement the following methods:
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/UnorderedContainers/task.md:82]: This task looks like a pretty simple wrapper around `std::unoredered_map`. 
Maybe, to make it more challenging, we can ask students to implement a simple LRU cache using `std::unordered_map` and `std::list`?

https://www.interviewcake.com/concept/java/lru-cache

File: StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+2. **Output Iterators**: Supports writing values to the pointed-to elements. Once written, the iterator can be incremented to point to the next element.
+3. **Forward Iterators**: Combines the features of both input and output iterators. Allows multiple passes through a range and supports both read and write operations.
+4. **Bidirectional Iterators**: Enhances forward iterators by adding the ability to move backward through a range using the `--` operator.
+5. **Random Access Iterators**: The most feature-rich iterators, providing constant time access to any element in the range, arithmetic operations, and pointer-like behavior.
+
+More information about the iterator categories, as well as comprehensive table, can be found in the [C++ reference](https://en.cppreference.com/w/cpp/iterator).
+
+Iterators can be invalidated by certain operations performed on the container it is tied to. Understanding iterator invalidation is crucial to avoid undefined behavior. Common scenarios leading to iterator invalidation are:
+ - **Insertion and Deletion**: Inserting or deleting elements in the container may invalidate iterators pointing to the modified elements.
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md:13]:
```suggestion
 - **Insertion and Deletion**: inserting or deleting elements in the container may invalidate iterators pointing to the modified elements.
```

File: StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+ - **Resizing the Container**: Resizing operations may cause reallocation, leading to the invalidation of all iterators.
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md:14]:
```suggestion
 - **Resizing the Container**: resizing operations may cause reallocation, leading to the invalidation of all iterators.
```

File: StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+ - **Clearing the Container**: Clearing the container invalidates all iterators pointing to its elements.
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md:15]:
```suggestion
 - **Clearing the Container**: clearing the container invalidates all iterators pointing to its elements.
```

File: StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md [hunk 5]
```diff
@@ -0,0 +1,60 @@
+Sometimes you will need to create your own iterators. For example, you may want to create an iterator that iterates over a custom data structure. In such cases, you will need to know how to create iterators that conform to the standard iterator categories. Different iterator categories are expected in different situations. For example, the algorithms in the STL require iterators that support the forward iterator category. If you want to use an algorithm that requires forward iterators, you will need to ensure that your custom iterator supports the forward iterator category.
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md:1]: Let's remove the part about "creating your own iterators". Is is quite an advanced topic. Let's focus on iterator categories from the user point of view, and describe what category of iterators is provided by each discussed STL container.

File: StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+In C++, iterators are classified into several categories based on their capabilities and behaviors. The primary iterator categories include:
+
+1. **Input Iterators**: Supports reading values from the pointed-to elements. Once read, the iterator can be incremented to point to the next element.
+2. **Output Iterators**: Supports writing values to the pointed-to elements. Once written, the iterator can be incremented to point to the next element.
+3. **Forward Iterators**: Combines the features of both input and output iterators. Allows multiple passes through a range and supports both read and write operations.
+4. **Bidirectional Iterators**: Enhances forward iterators by adding the ability to move backward through a range using the `--` operator.
+5. **Random Access Iterators**: The most feature-rich iterators, providing constant time access to any element in the range, arithmetic operations, and pointer-like behavior.
+
+More information about the iterator categories, as well as comprehensive table, can be found in the [C++ reference](https://en.cppreference.com/w/cpp/iterator).
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md:10]: Please add a (short version of) comparison table here.

File: StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md [hunk 7]
```diff
@@ -0,0 +1,60 @@
...
+
+Iterators can be invalidated by certain operations performed on the container it is tied to. Understanding iterator invalidation is crucial to avoid undefined behavior. Common scenarios leading to iterator invalidation are:
+ - **Insertion and Deletion**: Inserting or deleting elements in the container may invalidate iterators pointing to the modified elements.
+ - **Resizing the Container**: Resizing operations may cause reallocation, leading to the invalidation of all iterators.
+ - **Clearing the Container**: Clearing the container invalidates all iterators pointing to its elements.
+
+For more cases, please refer to this [article](http://kera.name/articles/2011/06/iterator-invalidation-rules-c0x/).
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md:17]: Please add a table, mapping each discussed STL container to the category of iterator it provides, and the invalidation rules for this container.

File: StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md [hunk 8]
```diff
@@ -0,0 +1,60 @@
...
+
+[Iterator traits](https://en.cppreference.com/w/cpp/iterator/iterator_traits) are used to obtain information about the iterator type. For example, the iterator traits can be used to determine the iterator category, the value type, and the difference type of an iterator.
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md:19]: Let's omit type traits topic from C++Basics course, it is quite and advanced topic (and it needs a more detailed and complete description anyway).

File: StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md [hunk 9]
```diff
@@ -0,0 +1,60 @@
...
+
+`std::iterator_traits` provide uniform interface to the properties of `LegacyIterator` types, which makes it possible to implement algorithms only in terms of iterators.
+
+The range-based for loop is a new feature introduced in C++11. It provides a concise way to iterate over a container using iterators. The range-based for loop is supported by all standard containers, as well as arrays and initializer lists. The syntax of the range-based for loop is as follows:
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md:23]: This info looks a bit out of place here. Let's maybe move it to earlier tasks?
For example, the first task that introduces the iterators.

File: StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md [hunk 10]
```diff
@@ -0,0 +1,60 @@
...
+```
+will print the same line both times:
+```
+0 1 2 3 4 5
+0 1 2 3 4 5
+```
+
+Consider using range-based for loops whenever possible, as they are more concise and less error-prone.
+
+Your task is to create a custom bidirectional iterator for vector of integers that supports the following operations:
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/IteratorCategories/task.md:55]: Creating new iterator is a bit challenging topic. 
Let's maybe remove this task completely, and make this step a pure theory step?

File: StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md [hunk 11]
```diff
@@ -0,0 +1,179 @@
+In addition to all that we have learned so far, the STL also provides a number of algorithms that can be used on a range of elements. These algorithms are implemented as functions that usually utilize iterators. In this task, we will look at some of the most commonly used algorithms. There are many more algorithms available in the STL, and you can find a complete list [here](https://en.cppreference.com/w/cpp/algorithm).
+We highly encourage you to explore the STL algorithms by yourself and try to use them in your code! They are useful and can save you a lot of time and effort.
+
+#### 1. `std::sort()`
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md:4]: Please mention iterators of which category each algorithm expects.

File: StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md [hunk 12]
```diff
@@ -0,0 +1,179 @@
...
+The [`std::sort()`](https://en.cppreference.com/w/cpp/algorithm/sort) algorithm is used to sort a range of elements. It is implemented as a function template of a `O(n log n)` sorting algorithm (most likely, [introsort](https://en.wikipedia.org/wiki/Introsort)), and the syntax is as follows:
+```cpp
+std::sort(start_iterator, end_iterator, comparator);
+```
+The first two arguments are iterators that define the range of elements to be sorted. The third argument is an optional comparator used to compare two elements. If no comparator is provided, the elements are sorted in ascending order by default. The comparator can be a function pointer, a lambda expression (small in-place function), or a functor.
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md:9]: lambdas were not properly introduced previously, so let's avoid mentioning them

File: StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md [hunk 13]
```diff
@@ -0,0 +1,179 @@
...
+    std::sort(v2.begin(), v2.end(), std::greater<>());
+    // v = {5, 4, 3, 2, 1}
+
+    // Sort a vector of strings in ascending order by length
+    std::vector<std::string> v3 = {"abc", "a", "ab"};
+    std::sort(v3.begin(), v3.end(), [](const std::string &a, const std::string &b) {
+        return a.size() < b.size();
+    });
+    // v = {"a", "ab", "abc"}
+}
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md:33]: One general notice for all code snippets like this used in this module. 
Please consider shortening them, and do not give the full code with all the includes, `main` declaration, etc.

File: StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md [hunk 14]
```diff
@@ -0,0 +1,179 @@
...
+
+int main() {
+    std::vector<int> v = {1, 2, 3, 4, 5, 6, 7, 8, 9};
+    long long sum = std::accumulate(v.begin(), v.end(), 0LL);
+    std::cout << "Sum: " << sum << std::endl;
+}
+```
+
+#### 2. `std::gcd()` and `std::lcm()`
+[`std::gcd()`](https://en.cppreference.com/w/cpp/numeric/gcd) and [`std::lcm()`](https://en.cppreference.com/w/cpp/numeric/lcm) are used to calculate the Greatest Common Divisor and the Least Common Multiple of two integers. They are implemented as `O(log n)` algorithms, looking like that:
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md:136]: You would not encounter `gcd` and `lcm` often in your code, so let's avoid mentioning them.

File: StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md [hunk 15]
```diff
@@ -0,0 +1,179 @@
...
+int main() {
+    int a = 12, b = 18;
+    std::cout << "GCD: " << std::gcd(a, b) << std::endl;
+    std::cout << "LCM: " << std::lcm(a, b) << std::endl;
+}
+```
+
+Finally, let's get some practice with these algorithms. Your task is to implement the following functions:
+ - `create_and_fill` - create a vector of size `n` and fill it with the values from `1` to `n` in ascending order.
+ - `shuffle_vector` - shuffle the elements of the vector.
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md:155]: `shuffle` is already available in STL.

https://en.cppreference.com/w/cpp/algorithm/random_shuffle

File: StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md [hunk 16]
```diff
@@ -0,0 +1,179 @@
...
+ - `sort_descending` - sort the elements of the vector in descending order.
+ - `reverse_vector` - reverse the elements of the vector.
+ - `find_value` - find the first occurrence of the value `x` in the vector.
+ - `find_sum` - calculate the sum of the elements in the vector.
+ - `find_gcd` - calculate the GCD of sum of the elements in the given vector and the value `x`.
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md:160]: Instead of this small tasks, let's think of a single, more complex task that would require to utilize several algorithms at once. 

For example, a function, that would calculate a sum of elements in the collection with values between two provided values `lowerBound` and `upperBound`. 

To implement this, the student will have to first sort the collection, then get two iterators using `find`, and finally use `accumulate` to calculate the sum.

File: StandardLibraryEssentials/StandardTemplateLibrary/InputOutputStreams/task.md [hunk 17]
```diff
@@ -0,0 +1,151 @@
+In C++, input/output (I/O) operations are performed using streams. A stream is a sequence of bytes that flow from a source (like a keyboard, a file, or a network connection) to a destination (like a screen, a file, or a network connection). The C++ Standard Library provides several classes for performing I/O operations. Their hierarchy is shown [here](https://en.cppreference.com/w/cpp/io#Hierarchy). 
+
+The most basic stream types are the input stream type `istream` and the output stream type `ostream`. These two types create a `iostream` type, which is the type of the standard input stream `std::cin` and the standard output stream `std::cout`. The `istream` type provides overloaded `>>` operator for input and the `ostream` type provides overloaded `<<` operator for output.
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/InputOutputStreams/task.md:3]: what is `iostream` type?

`std::cout` is `ostream`, while `std::cin` is `istream`

File: StandardLibraryEssentials/StandardTemplateLibrary/InputOutputStreams/task.md [hunk 18]
```diff
@@ -0,0 +1,151 @@
...
+```
+
+You need to create a program that reads all input string by string, until the string "end" is read. After that, the program should output responses on each token in the following format:
+
+ - If the number is read, the program should output "Got number: <number>" with precision of 3 decimal places.
+ - If token is not a number, the program should output "Got string: <string>".
+
+We encourage you to use stringstream for parsing the input and collecting tokens, since it is the most efficient way to change string dynamically.
+
+A number is a sequence of digits, optionally containing one decimal point and minus sign at the beginning.
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/InputOutputStreams/task.md:151]: Put this paragraph under hint.

**Review by eupp — CHANGES_REQUESTED** [review]

**Comment by boruno** [comment]
Last task of Templates module may be a bit controversial in terms of covered information, since I’ve included a brief explanation of type traits and variadic templates to it. I haven’t came up with anything else that could be presented in this lesson, other than basic template specialization idea. I don't mind deleting this part, but I thought it may be a nice sneak peek to metaprogramming and other high-level stuff.

File: StandardLibraryEssentials/Templates/Introduction/task.md [hunk 19]
```diff
@@ -0,0 +1,9 @@
+In this part of the course, you will learn about such a feature of the C++ language as templates.
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/Introduction/task.md:1]:
```suggestion
In this part of the course, you will learn about the templates in the C++ language.
```

File: StandardLibraryEssentials/Templates/Introduction/task.md [hunk 20]
```diff
@@ -0,0 +1,9 @@
...
+
+In essence, templates are a means to write generic code that can work with varying types. They allow you to write a single function or class that can adapt to different types, without the need to write separate functions or classes for each type.
+
+The following topics will be covered:
+ * Definition of templates for functions and classes
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/Introduction/task.md:6]:
```suggestion
 * Template functions and classes 
```

File: StandardLibraryEssentials/Templates/Introduction/task.md [hunk 21]
```diff
@@ -0,0 +1,9 @@
+In this part of the course, you will learn about such a feature of the C++ language as templates.
+
+In essence, templates are a means to write generic code that can work with varying types. They allow you to write a single function or class that can adapt to different types, without the need to write separate functions or classes for each type.
+
+The following topics will be covered:
+ * Definition of templates for functions and classes 
+ * Type-inference, `auto` and `decltype` keywords, template argument deduction
+ * Type aliases: `using` and `typedef`
+ * Template specialization
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/Introduction/task.md:9]: * Type inference: `auto` and `decltype`
* Template argument deduction
* Type aliases: `using` and `typedef`
* Template specialization

File: StandardLibraryEssentials/Templates/TemplateBasics/task.md [hunk 22]
```diff
@@ -0,0 +1,75 @@
+Imagine that you have a function for calculating the sum of two numbers. If you want to calculate the sum of two integers, you can write a function that takes two `int` numbers as arguments and returns their sum. However, suppose you also want to have such a function for `double`, `long long`, `float`, and a custom type such as `Fraction`. You will have to write a separate function for each type. This becomes inconvenient, as you end up writing multiple functions that essentially do the same thing but with different data types.
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TemplateBasics/task.md:1]:
```suggestion
Imagine that you have a function for calculating the sum of two numbers. If you want to calculate the sum of two integers, you can write a function that takes two `int` numbers as arguments and returns their sum. However, suppose you also want to have such a function for `double`, `long long`, `float`, or some custom data type. You will have to write a separate function for each type. This becomes inconvenient, as you end up writing multiple functions that essentially do the same thing but with different data types.
```

File: StandardLibraryEssentials/Templates/TemplateBasics/task.md [hunk 23]
```diff
@@ -0,0 +1,75 @@
...
+
+Templates are designed to address this exact issue. They allow you to write a single function that can work with different types. For instance, you can write a template function that takes two arguments of any type and returns their sum as a variable of the same type.
+
+The syntax for creating a template function is simple: you start with the `template` keyword, followed by the `typename` keyword, and then include the type name you want to use as a template parameter. Then, you can use this type name in the function as if it were a regular type:
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TemplateBasics/task.md:5]:
```suggestion
The syntax for creating a template function is simple: you start with the `template` keyword, followed by the `typename` keyword, and then include the type name you want to use as a template parameter. Then, you can use this type name in the function as if it was a regular type:
```

File: StandardLibraryEssentials/Templates/TemplateBasics/task.md [hunk 24]
```diff
@@ -0,0 +1,75 @@
...
+```
+
+The number of template parameters is not limited to one. If you need to use multiple types for the function arguments, you can apply several template parameters. This is an example function featuring two:
+```cpp
+template <typename T1, typename T2>
+T1 sum(T1 a, T2 b) {
+    return a + b;
+}
+```
+This function will work with types such that the second type can be cast to the first type, and it supports the `+` operator. Note that the return type of the function is `T1`, so the result of the sum will be of the same type as the first argument.
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TemplateBasics/task.md:21]:
```suggestion
This function will work with any pair of types, as long as the first type supports the `+` operator and the second type can be cast to the first type. Note that the return type of the function is `T1`, so the result of the sum will be of the same type as the first argument.
```

File: StandardLibraryEssentials/Templates/TemplateBasics/task.md [hunk 25]
```diff
@@ -0,0 +1,75 @@
...
+
+<div class="hint">
+    You can use `std::is_same` to check if two types are the same. This can be useful when you want to restrict the types that can be used with the template function.
+</div>
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TemplateBasics/task.md:25]: We have not introduced type traits, it is a separate complicated topic, let's omit it here.

File: StandardLibraryEssentials/Templates/TemplateBasics/task.md [hunk 26]
```diff
@@ -0,0 +1,75 @@
...
+
+Templates can also be used with classes. You can create a class template that can work with different types. The syntax is similar to the function template, but you need to specify the template parameters after the class name:
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TemplateBasics/task.md:27]:
```suggestion
Templates can also be used with classes. You can create a class template that can work with different types. The syntax is similar to the function template, but you need to specify the template parameters before the class name:
```

File: StandardLibraryEssentials/Templates/TemplateBasics/task.md [hunk 27]
```diff
@@ -0,0 +1,75 @@
...
+```cpp
+int sum(int a, int b) {
+    return a + b;
+}
+```
+and uses it to calculate the sum of two integers.
+
+The same process applies to class templates. The key point is that a separate function or class is generated for each type with which a template is used, which is why templates are a compile-time feature.
+
+Sometimes, you may face a template declaration using the `class` keyword instead of `typename`. Both keywords are interchangeable in template declarations, and in most cases, you can use either. However, there are a few exceptions. For more information, refer to [this article](https://mariusbancila.ro/blog/2021/03/15/typename-or-class/).
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TemplateBasics/task.md:66]: Put this paragraph under a hint.

File: StandardLibraryEssentials/Templates/TemplateBasics/task.md [hunk 28]
```diff
@@ -0,0 +1,75 @@
...
+
+In this task, you need to implement an analog of the [`std::pair`](https://en.cppreference.com/w/cpp/utility/pair) class. In essence, it should be a class with two template parameters, `T1` and `T2`, and two fields of these types, to store two values simultaneously.
+Usually, when implementing templates in C++, you need to include the implementation in the header file. Go to the `/include/DataPair.hpp` file and create the `DataPair` class template there. The class should have the following methods:
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TemplateBasics/task.md:69]:
```suggestion
Go to the `/include/DataPair.hpp` file and create the `DataPair` class template there. The class should have the following methods:
```

File: StandardLibraryEssentials/Templates/TypeInference/task.md [hunk 29]
```diff
@@ -0,0 +1,49 @@
+Type inference is a powerful feature in C++ that allows the compiler to automatically deduce the type of a variable or expression at compile time. This can make your code more concise and easier to read, as well as reduce the likelihood of type-related errors. When dealing with types with complex and obscure names, type inference can make your code more readable and maintainable.
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TypeInference/task.md:1]:
```suggestion
Type inference is a powerful feature in C++ that allows the compiler to automatically deduce the type of a variable or an expression at compile time. This can make your code more concise and easier to read, as well as reduce the likelihood of type-related errors. When dealing with types with complex and obscure names, type inference can make your code more readable and maintainable.
```

File: StandardLibraryEssentials/Templates/TypeInference/task.md [hunk 30]
```diff
@@ -0,0 +1,49 @@
...
+
+It is important to note that type inference is not the same as dynamic typing, a feature characteristic of languages like Python and JavaScript. In C++, a variable's type is determined once and remains unchanged until its destruction. 
+
+Type inference is a compile-time feature where the type of a variable or expression is determined based on the context of its usage. Thus, compilation time might slightly increase when using type inference, but the resulting code will be more concise and easier to read.
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TypeInference/task.md:5]: I suggest removing this paragraph:

> Thus, compilation time might slightly increase when using type inference, but the resulting code will be more concise and easier to read.

I do not think the compilation time would be significantly different for the majority of the cases. This paragraph can only scare away the students from this feature.

File: StandardLibraryEssentials/Templates/TypeInference/task.md [hunk 31]
```diff
@@ -0,0 +1,49 @@
...
+auto& ref2 = ref; // ref2 is deduced to be an int&
+```
+
+Another new keyword introduced in C++11 is `decltype`, which allows you to deduce the type of expression without actually evaluating it. This can be useful when you want to declare a variable with the same type as another expression:
+```cpp
+int a = 42;
+decltype(a) b = 3 + a; // b is deduced to be an int
+```
+
+Sometimes, you may encounter `decltype(auto)`, which deduces the type of a variable or an expression using `decltype` rules. This can be useful when you want to retain the reference or const-qualification of the original expression. `auto` follows the template argument deduction rules and always assumes an object type, while `decltype(auto)` follows `decltype` rules to deduce reference types based on value categories.
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TypeInference/task.md:28]: Let's remove this paragraph and example. It is a bit too much complicated for the novice C++ learners.

File: StandardLibraryEssentials/Templates/TypeInference/task.md [hunk 32]
```diff
@@ -0,0 +1,49 @@
...
+```cpp
+int a = 42;
+const int& ref = a;
+auto b = ref; // b is deduced to be an int
+decltype(auto) c = ref; // c is deduced to be a const int&
+```
+
+For both function and class templates, the compiler can often deduce the types of the template arguments from the types of the provided arguments. This means that you don't always have to explicitly specify the template arguments when calling a function template. Here's how you can use template argument deduction:
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TypeInference/task.md:36]:
```suggestion
For both function and class templates, the compiler can often deduce the types of the template arguments from the types of the provided arguments. This means that you don't always have to explicitly specify the template arguments when calling a function template. This feature is called _template argument deduction_. Here's how it can be used:
```

File: StandardLibraryEssentials/Templates/TypeAliases/task.md [hunk 33]
```diff
@@ -0,0 +1,58 @@
...
+Type aliases can also be used to create a more readable name for a complex type. For example, you can create a type alias for this complex type:
+```cpp
+std::pair<std::pair<int, int>, std::pair<std::string, std::string>> complex_type;
+
+// Using type alias
+using ComplexType = std::pair<std::pair<int, int>, std::pair<std::string, std::string>>;
+ComplexType complex_type;
+```
+
+Note that type aliases follow the same scope rules as regular types. They are only valid within the scope in which they are defined. This means that if you define a type alias inside a function, it will only be accessible within that function.
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TypeAliases/task.md:33]: We haven't studies scoped type declarations, so let's remove this paragraph.

File: StandardLibraryEssentials/Templates/TypeAliases/task.md [hunk 34]
```diff
@@ -0,0 +1,58 @@
...
+long long function() {
+    using ll = long long;
+    ll x = 1'234'567'890'987'654'321; // This is fine
+    ...
+}
+
+ll y = 1'234'567'890'987'654'321; // Error: 'll' was not declared in this scope
+```
+
+When you encounter lines like `using namespace std;` in code. It's not a type alias; instead, it's a directive that tells the compiler to extend the current scope to include all the names from the `std` namespace into your current scope. Although this could save you from typing `std::` before every standard library function or object, it's considered bad practice to use `using namespace std;` in your code. The reason is that it can lead to naming conflicts. If you utilize `using namespace std;` and create a function or class with a name that already exists in the `std` namespace, you will get a compilation error:
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TypeAliases/task.md:44]: Let's delay this to the following modules when we will introduce namespaces.

File: StandardLibraryEssentials/Templates/TypeAliases/task.md [hunk 35]
```diff
@@ -0,0 +1,58 @@
...
+The `using` keyword, introduced in C++11, offers a more modern way to create type aliases. It is used in the same way, but the syntax is simpler and more readable than `typedef`. The format is: ```using <desired_type_name> = <current_type_name>;```. Here is how you can utilize `using` to create a type alias for `long long`:
+```cpp
+using ll = long long;
+ll x = 1'234'567'890'987'654'321;
+```
+
+On top of that, `using` can be employed to create type aliases for templates. This is especially useful when you want to create a type alias for a template with multiple parameters. Here's an example of how you can leverage `using` to create a type alias for a `std::vector` of `int` type (an upgraded version of an array, which will be covered in the next module):
+```cpp
+template <typename T>
+using Arr = std::vector<T>;
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TypeAliases/task.md:18]: Let's avoid using `std::vector` here, because it was not yet introduced. 
We can use `std::unique_ptr` as an example, because it was already mentioned before:

```
template <typename T>
using unique_array = std::unique_ptr<T[]>
```

File: StandardLibraryEssentials/Templates/TemplateSpecialization/task.md [hunk 36]
```diff
@@ -0,0 +1,61 @@
...
+void print(T value) {
+    if (std::is_pointer<T>::value) {
+        std::cout << *value << std::endl;
+    } else {
+        std::cout << value << std::endl;
+    }
+}
+```
+
+If the number of parameters is unknown, you can use variadic templates. This allows you to create a function that can take any number of arguments of any type. The syntax is a bit more complex, but it is still quite simple:
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TemplateSpecialization/task.md:41]: Let's move info about variadic templates into the first task, where the templates are introduced.

Comment (eupp) [inline StandardLibraryEssentials/Templates/TemplateSpecialization/task.md:41]: > The syntax is a bit more complex, but it is still quite simple

This sentence does not make sense, let's remove it.

File: StandardLibraryEssentials/Templates/TemplateSpecialization/task.md [hunk 37]
```diff
@@ -0,0 +1,61 @@
...
+template <>
+void print<int*>(int* value) {
+    std::cout << *value << std::endl;
+}
+
+int main() {
+    int a = 5;
+    int* b = &a;
+    print(a); // prints 5
+    print(b); // prints the value of the pointer
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TemplateSpecialization/task.md:19]:
```suggestion
    print(b); // also prints 5 --- the pointed-to value
```

File: StandardLibraryEssentials/Templates/TemplateSpecialization/task.md [hunk 38]
```diff
@@ -0,0 +1,61 @@
...
+    return 0;
+}
+```
+
+When the compiler encounters any call to a template function, it first checks for a specialized version of the function for the argument's type. If such a version exists, it will employ it; otherwise, it will use the general version.
+
+There is a technique called metaprogramming, which allows you to write code that generates other code using templates and template specialization. Since it is a complex topic, we will not cover it in this course, but you can find more information about it in the [C++ documentation](https://en.cppreference.com/w/cpp/meta). However, there is a feature called "type traits" that can be helpful in some cases. Type traits are a set of classes that provide information about types at compile time. You can use them to check if a type has a specific property, like being a pointer or reference. You can find more information about type traits in the [C++ documentation](https://en.cppreference.com/w/cpp/header/type_traits).
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TemplateSpecialization/task.md:26]: Let's not mention "type traits". It is a complicated feature, which can only confuse novice programmers. This feature deserves its own series of tasks and should be properly explained.

File: StandardLibraryEssentials/Templates/TemplateSpecialization/task.md [hunk 39]
```diff
@@ -0,0 +1,61 @@
...
+
+Since each specialization requires a separate implementation, it may not always be the best solution. In many cases, you can try to find any common type property and use it's checker, like the `std::is_pointer` function to check if the type is a pointer and handle it within the general function. This way, you can avoid code duplication and make the code more readable.
```
Comment (eupp) [inline StandardLibraryEssentials/Templates/TemplateSpecialization/task.md:28]: Let's remove this paragraph and example too.

File: StandardLibraryEssentials/StandardTemplateLibrary/UnorderedContainers/task.md [hunk 40]
```diff
@@ -0,0 +1,96 @@
...
+This, however, is a small price to pay for the `O(1)` complexity of the search, insertion, and deletion operations. 
+
+The main methods of `std::unordered_set` and `std::unordered_map` include:
+* `insert(value)` - inserts the element `value` into the container
+* `emplace(args...)` - constructs the element in-place
+* `erase(value)` - removes the element `value` from the container
+* `find(value)` - returns an iterator to the element `value` if it is found, otherwise, it returns `end()`
+
+To be fair, all these methods have **amortized** `O(1)` complexity, since sometimes hashes of different keys can be the same. This is called a [collision](https://en.wikipedia.org/wiki/Hash_table#Collision_resolution). In such situations, the whole table needs to be rehashed, which is the reason why the methods of an unordered container can perform in `O(n)` time in the worst-case scenario.
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/UnorderedContainers/task.md:13]: Move this paragraph after the next two paragraphs (about hash table and `std::hash`), and put it under a hint.

File: StandardLibraryEssentials/StandardTemplateLibrary/UnorderedContainers/task.md [hunk 41]
```diff
@@ -0,0 +1,96 @@
...
+    // }
+    
+    // print all elements, order is not guaranteed
+    for (const auto& s : set) {
+        std::cout << s << std::endl;
+    }
+}
+```
+
+You need to implement a [cache](https://en.wikipedia.org/wiki/Cache_(computing)) system with an [LRU](https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)) (Least Recently Used) policy. Its member functions are defined in the `/include/Cache.h` file. Since cache is a very fast type of storage, you will need to use hashing to implement it. The provided solution uses `std::list` and `std::unordered_map`, but you can choose any container from the STL for your own implementation. At first, define a structure inside `/include/Cache.h` file that will store key-value pairs. Then, define another structure that will store the key and an iterator to the corresponding element in the list. After defining these structures, you can implement the cache operations on `task.cpp`.
```
Comment (eupp) [inline StandardLibraryEssentials/StandardTemplateLibrary/UnorderedContainers/task.md:87]: > The provided solution uses `std::list` and `std::unordered_map`, but you can choose any container from the STL for your own implementation.

Maybe let's remove this suggestion? I think it can only confuse the students. 
Using just `std::list` and `std::unordered_map` is fine for this task.

File: StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md (hunk 11 above)
Comment (eupp) [reply StandardLibraryEssentials/StandardTemplateLibrary/STLAlgorithms/task.md:4]: This comment is still relevant (there is still no mentioned of iterators categories expected by the algorithms).

**Review by eupp — CHANGES_REQUESTED** [review]
