### ISSUE TITLE
Moving on, Starting the game issue on mac m1

### ISSUE THREAD

**Issue by stormbreakercod** [jetbrains-academy/CppBasics#75]
ive installed SMFL, and it says everthing is working in terminal, but when i run the starting the game file, i get a bunch of errors, chatgpt says the cmake on clion and the course is using a different version as the on that is installed from homebrew? here is the errors: ===================[ Build | WarmUp-MovingOn-StartTheGame-run | Debug ]========
/Users/eitanmirochnik/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake --build /Users/eitanmirochnik/CLionProjects/C++Basics/cmake-build-debug --target WarmUp-MovingOn-StartTheGame-run -- -j 6
[  0%] Building CXX object WarmUp/MovingOn/task/CMakeFiles/WarmUp-MovingOn-StartTheGame-run.dir/src/empty.cpp.o
[100%] Building CXX object WarmUp/MovingOn/task/CMakeFiles/WarmUp-MovingOn-StartTheGame-run.dir/src/main.cpp.o
In file included from /Users/eitanmirochnik/CLionProjects/C++Basics/WarmUp/MovingOn/task/src/main.cpp:3:
In file included from /opt/homebrew/include/SFML/Graphics.hpp:32:
In file included from /opt/homebrew/include/SFML/Graphics/CircleShape.hpp:32:
In file included from /opt/homebrew/include/SFML/Graphics/Shape.hpp:32:
In file included from /opt/homebrew/include/SFML/Graphics/Color.hpp:229:
/opt/homebrew/include/SFML/Graphics/Color.inl:77:16: error: variable of non-literal type 'const (lambda at /opt/homebrew/include/SFML/Graphics/Color.inl:77:29)' cannot be defined in a constexpr function before C++23
   77 |     const auto clampedAdd = [](std::uint8_t lhs, std::uint8_t rhs)
      |                ^
/opt/homebrew/include/SFML/Graphics/Color.inl:77:29: note: lambda closure types are non-literal types before C++17
   77 |     const auto clampedAdd = [](std::uint8_t lhs, std::uint8_t rhs)
      |                             ^
/opt/homebrew/include/SFML/Graphics/Color.inl:93:16: error: variable of non-literal type 'const (lambda at /opt/homebrew/include/SFML/Graphics/Color.inl:93:29)' cannot be defined in a constexpr function before C++23
   93 |     const auto clampedSub = [](std::uint8_t lhs, std::uint8_t rhs)
      |                ^
/opt/homebrew/include/SFML/Graphics/Color.inl:93:29: note: lambda closure types are non-literal types before C++17
   93 |     const auto clampedSub = [](std::uint8_t lhs, std::uint8_t rhs)
      |                             ^
/opt/homebrew/include/SFML/Graphics/Color.inl:109:16: error: variable of non-literal type 'const (lambda at /opt/homebrew/include/SFML/Graphics/Color.inl:109:28)' cannot be defined in a constexpr function before C++23
  109 |     const auto scaledMul = [](std::uint8_t lhs, std::uint8_t rhs)
      |                ^
/opt/homebrew/include/SFML/Graphics/Color.inl:109:28: note: lambda closure types are non-literal types before C++17
  109 |     const auto scaledMul = [](std::uint8_t lhs, std::uint8_t rhs)
      |                            ^
/opt/homebrew/include/SFML/Graphics/Color.inl:146:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  146 | inline constexpr Color Color::Black(0, 0, 0);
      | ^
/opt/homebrew/include/SFML/Graphics/Color.inl:147:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  147 | inline constexpr Color Color::White(255, 255, 255);
      | ^
/opt/homebrew/include/SFML/Graphics/Color.inl:148:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  148 | inline constexpr Color Color::Red(255, 0, 0);
      | ^
/opt/homebrew/include/SFML/Graphics/Color.inl:149:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  149 | inline constexpr Color Color::Green(0, 255, 0);
      | ^
/opt/homebrew/include/SFML/Graphics/Color.inl:150:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  150 | inline constexpr Color Color::Blue(0, 0, 255);
      | ^
/opt/homebrew/include/SFML/Graphics/Color.inl:151:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  151 | inline constexpr Color Color::Yellow(255, 255, 0);
      | ^
/opt/homebrew/include/SFML/Graphics/Color.inl:152:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  152 | inline constexpr Color Color::Magenta(255, 0, 255);
      | ^
/opt/homebrew/include/SFML/Graphics/Color.inl:153:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  153 | inline constexpr Color Color::Cyan(0, 255, 255);
      | ^
/opt/homebrew/include/SFML/Graphics/Color.inl:154:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  154 | inline constexpr Color Color::Transparent(0, 0, 0, 0);
      | ^
In file included from /Users/eitanmirochnik/CLionProjects/C++Basics/WarmUp/MovingOn/task/src/main.cpp:3:
In file included from /opt/homebrew/include/SFML/Graphics.hpp:32:
In file included from /opt/homebrew/include/SFML/Graphics/CircleShape.hpp:32:
In file included from /opt/homebrew/include/SFML/Graphics/Shape.hpp:35:
In file included from /opt/homebrew/include/SFML/Graphics/Rect.hpp:30:
In file included from /opt/homebrew/include/SFML/System/Vector2.hpp:29:
In file included from /opt/homebrew/include/SFML/System/Angle.hpp:475:
/opt/homebrew/include/SFML/System/Angle.inl:272:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  272 | inline constexpr Angle Angle::Zero;
      | ^
In file included from /Users/eitanmirochnik/CLionProjects/C++Basics/WarmUp/MovingOn/task/src/main.cpp:3:
In file included from /opt/homebrew/include/SFML/Graphics.hpp:32:
In file included from /opt/homebrew/include/SFML/Graphics/CircleShape.hpp:32:
In file included from /opt/homebrew/include/SFML/Graphics/Shape.hpp:35:
/opt/homebrew/include/SFML/Graphics/Rect.hpp:98:34: error: no template named 'optional' in namespace 'std'
   98 |     [[nodiscard]] constexpr std::optional<Rect<T>> findIntersection(const Rect<T>& rectangle) const;
      |                             ~~~~~^
In file included from /Users/eitanmirochnik/CLionProjects/C++Basics/WarmUp/MovingOn/task/src/main.cpp:3:
In file included from /opt/homebrew/include/SFML/Graphics.hpp:32:
In file included from /opt/homebrew/include/SFML/Graphics/CircleShape.hpp:32:
In file included from /opt/homebrew/include/SFML/Graphics/Shape.hpp:35:
In file included from /opt/homebrew/include/SFML/Graphics/Rect.hpp:151:
/opt/homebrew/include/SFML/Graphics/Rect.inl:71:16: error: no template named 'optional' in namespace 'std'
   71 | constexpr std::optional<Rect<T>> Rect<T>::findIntersection(const Rect<T>& rectangle) const
      |           ~~~~~^
/opt/homebrew/include/SFML/Graphics/Rect.inl:103:17: error: no member named 'nullopt' in namespace 'std'
  103 |     return std::nullopt;
      |            ~~~~~^
In file included from /Users/eitanmirochnik/CLionProjects/C++Basics/WarmUp/MovingOn/task/src/main.cpp:3:
In file included from /opt/homebrew/include/SFML/Graphics.hpp:32:
In file included from /opt/homebrew/include/SFML/Graphics/CircleShape.hpp:32:
In file included from /opt/homebrew/include/SFML/Graphics/Shape.hpp:36:
In file included from /opt/homebrew/include/SFML/Graphics/RenderStates.hpp:35:
In file included from /opt/homebrew/include/SFML/Graphics/Transform.hpp:352:
/opt/homebrew/include/SFML/Graphics/Transform.inl:101:16: error: use of class template 'std::array' requires template arguments
  101 |     const std::array points = {transformPoint(rectangle.position),
      |                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX15.4.sdk/usr/include/c++/v1/array:169:29: note: template is declared here
  168 | template <class _Tp, size_t _Size>
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  169 | struct _LIBCPP_TEMPLATE_VIS array {
      |                             ^
In file included from /Users/eitanmirochnik/CLionProjects/C++Basics/WarmUp/MovingOn/task/src/main.cpp:3:
In file included from /opt/homebrew/include/SFML/Graphics.hpp:32:
In file included from /opt/homebrew/include/SFML/Graphics/CircleShape.hpp:32:
In file included from /opt/homebrew/include/SFML/Graphics/Shape.hpp:36:
In file included from /opt/homebrew/include/SFML/Graphics/RenderStates.hpp:35:
In file included from /opt/homebrew/include/SFML/Graphics/Transform.hpp:352:
/opt/homebrew/include/SFML/Graphics/Transform.inl:234:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  234 | inline constexpr Transform Transform::Identity;
      | ^
In file included from /Users/eitanmirochnik/CLionProjects/C++Basics/WarmUp/MovingOn/task/src/main.cpp:3:
In file included from /opt/homebrew/include/SFML/Graphics.hpp:36:
In file included from /opt/homebrew/include/SFML/Graphics/Font.hpp:34:
/opt/homebrew/include/SFML/Graphics/Texture.hpp:114:33: error: no member named 'filesystem' in namespace 'std'
  114 |     explicit Texture(const std::filesystem::path& filename, bool sRgb = false);
      |                            ~~~~~^
/opt/homebrew/include/SFML/Graphics/Texture.hpp:137:24: error: no member named 'filesystem' in namespace 'std'
  137 |     Texture(const std::filesystem::path& filename, bool sRgb, const IntRect& area);
      |                   ~~~~~^
/opt/homebrew/include/SFML/Graphics/Texture.hpp:304:48: error: no member named 'filesystem' in namespace 'std'
  304 |     [[nodiscard]] bool loadFromFile(const std::filesystem::path& filename, bool sRgb = false, const IntRect& area = {});
      |                                           ~~~~~^
In file included from /Users/eitanmirochnik/CLionProjects/C++Basics/WarmUp/MovingOn/task/src/main.cpp:3:
In file included from /opt/homebrew/include/SFML/Graphics.hpp:36:
/opt/homebrew/include/SFML/Graphics/Font.hpp:103:30: error: no member named 'filesystem' in namespace 'std'
  103 |     explicit Font(const std::filesystem::path& filename);
      |                         ~~~~~^
/opt/homebrew/include/SFML/Graphics/Font.hpp:168:48: error: no member named 'filesystem' in namespace 'std'
  168 |     [[nodiscard]] bool openFromFile(const std::filesystem::path& filename);
      |                                           ~~~~~^
In file included from /Users/eitanmirochnik/CLionProjects/C++Basics/WarmUp/MovingOn/task/src/main.cpp:3:
In file included from /opt/homebrew/include/SFML/Graphics.hpp:38:
/opt/homebrew/include/SFML/Graphics/Image.hpp:103:31: error: no member named 'filesystem' in namespace 'std'
  103 |     explicit Image(const std::filesystem::path& filename);
      |                          ~~~~~^
/opt/homebrew/include/SFML/Graphics/Image.hpp:175:48: error: no member named 'filesystem' in namespace 'std'
  175 |     [[nodiscard]] bool loadFromFile(const std::filesystem::path& filename);
      |                                           ~~~~~^
/opt/homebrew/include/SFML/Graphics/Image.hpp:227:46: error: no member named 'filesystem' in namespace 'std'
  227 |     [[nodiscard]] bool saveToFile(const std::filesystem::path& filename) const;
      |                                         ~~~~~^
/opt/homebrew/include/SFML/Graphics/Image.hpp:245:24: error: no template named 'optional' in namespace 'std'
  245 |     [[nodiscard]] std::optional<std::vector<std::uint8_t>> saveToMemory(std::string_view format) const;
      |                   ~~~~~^
In file included from /Users/eitanmirochnik/CLionProjects/C++Basics/WarmUp/MovingOn/task/src/main.cpp:3:
In file included from /opt/homebrew/include/SFML/Graphics.hpp:45:
In file included from /opt/homebrew/include/SFML/Graphics/RenderWindow.hpp:36:
In file included from /opt/homebrew/include/SFML/Window/Window.hpp:32:
In file included from /opt/homebrew/include/SFML/Window/WindowBase.hpp:36:
In file included from /opt/homebrew/include/SFML/System/Time.hpp:447:
/opt/homebrew/include/SFML/System/Time.inl:282:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
  282 | inline constexpr Time Time::Zero;
      | ^
In file included from /Users/eitanmirochnik/CLionProjects/C++Basics/WarmUp/MovingOn/task/src/main.cpp:3:
In file included from /opt/homebrew/include/SFML/Graphics.hpp:45:
In file included from /opt/homebrew/include/SFML/Graphics/RenderWindow.hpp:36:
In file included from /opt/homebrew/include/SFML/Window/Window.hpp:32:
/opt/homebrew/include/SFML/Window/WindowBase.hpp:226:24: error: no template named 'optional' in namespace 'std'
  226 |     [[nodiscard]] std::optional<Event> pollEvent();
      |                   ~~~~~^
/opt/homebrew/include/SFML/Window/WindowBase.hpp:252:24: error: no template named 'optional' in namespace 'std'
  252 |     [[nodiscard]] std::optional<Event> waitEvent(Time timeout = Time::Zero);
      |                   ~~~~~^
/opt/homebrew/include/SFML/Window/WindowBase.hpp:387:36: error: no template named 'optional' in namespace 'std'
  387 |     void setMinimumSize(const std::optional<Vector2u>& minimumSize);
      |                               ~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
12 warnings and 20 errors generated.
make[3]: *** [WarmUp/MovingOn/task/CMakeFiles/WarmUp-MovingOn-StartTheGame-run.dir/src/main.cpp.o] Error 1
make[2]: *** [WarmUp/MovingOn/task/CMakeFiles/WarmUp-MovingOn-StartTheGame-run.dir/all] Error 2
make[1]: *** [WarmUp/MovingOn/task/CMakeFiles/WarmUp-MovingOn-StartTheGame-run.dir/rule] Error 2
make: *** [WarmUp-MovingOn-StartTheGame-run] Error 2

**Comment by dacoty** [comment]
i have an M2 macbook and i have the exact same issue. this class uses 2.x sfml and i have 3.x sfml so i had to dive a bit into the migration guide here: https://www.sfml-dev.org/tutorials/3.0/getting-started/migrate/ and honestly, im preferring using the tutorials here over this cppbasics class.

**Comment by polinaburiak** [comment]
Hi @stormbreakercod, I'm sorry to hear that the experience with this course was confusing for you. 
 
There can indeed be an issue with the SFML library. Unfortunately, the course isn’t currently optimized to work with SFML 3.0.0, but we're working on improving it. 

The quickest way to continue with the course would be to install version 2.5.1 of SFML: https://www.sfml-dev.org/download/sfml/2.5.1/ Before doing so, please make sure to uninstall version 3.0.0 to avoid any conflicts. Also, please make sure that the project has been imported correctly. For that, go to **File | Reload CMake Project**.
